### ISSUE TITLE
suggestion for statisticalTests.R

### ISSUE THREAD

**Issue by jtremblay** [xiaosaiyao/epiregulon.extra#1]
[epiregulon.extra](https://github.com/xiaosaiyao/epiregulon.extra/tree/master)/[R](https://github.com/xiaosaiyao/epiregulon.extra/tree/master/R)
/statisticalTests.R

At line 129 of statisticalTests.R, I'd suggest implementing the following modification in order to check for cases were targets might not exist in gene list.

```
...
 if(all(!genesets$genes %in% regulon.TF)){ # check if no targets exist in genesets. if not, return empty data frame. Otherwise, clusterProfiler will crash.
            results <- data.frame(p.adjust = NA, Description = NA, GeneRatio = 0, Odds.Ratio = NA)
        }else{
            enrichresults <- clusterProfiler::enricher(regulon.TF, TERM2GENE = genesets)
...
```

**Comment by xiaosaiyao** [comment]
changes incorporated

https://github.com/xiaosaiyao/epiregulon.extra/blob/ae13577711d8323e2961e4ce982c90959ff8202a/R/statisticalTests.R#L141
